# Generated by Django 4.1.3 on 2022-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='facility',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='address',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
    ]
